version: '3.8'
services:
  kusama:
    container_name: 'kusama_node'
#    image: polkasource/substrate-client:kusama-latest
    image: parity/polkadot:latest
    logging:
      driver: "json-file"
      options:
        max-size: "100M"
        max-file: "2"
    volumes:
      - ./data_ksmcc3:/polkadot
    ports:
      - "127.0.0.1:9933:9933"
      - "0.0.0.0:9944:9944"
      - "127.0.0.1:30333:30333"
    command: ['--chain','kusama','--name', 'KodaDot','--out-peers','30','--in-peers','30','--ws-external','--rpc-external','--rpc-cors','all', '--wasm-execution=Compiled' ]
