version: '3.6'
services:
  kusama:
    container_name: 'local_node'
#    image: polkasource/substrate-client:kusama-latest
    image: parity/polkadot:latest
    logging:
      driver: "json-file"
      options:
        max-size: "100M"
        max-file: "2"
    volumes:
      - ./data_local_alice:/data/chains
    ports:
      - "0.0.0.0:9933:9933"
      - "0.0.0.0:9944:9944"
      - "127.0.0.1:30333:30333"
    command: ['--dev','--ws-external','--rpc-cors','all', '--wasm-execution=Compiled','--alice', '--rpc-methods=Unsafe']
